version: "3.9"
services:
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        ports:
#            - '8080:80'
#        restart: always
#        environment:
#            PMA_HOST: db
#        depends_on:
#            - db
    rara:
        container_name: rara
        image: rara/system:dev
        build:
            context: .
            dockerfile: system/Dockerfile_dev
            network: host
            args:
                app_env: dev
        env_file: system/.env.local
        working_dir: /opt/www
        volumes:
            - ./system/:/opt/www
        ports:
            - "72:8000"
        networks:
            - squareDev
networks:
    squareDev:
        external: true
